<?php

/*
  Modo de uso:

  <?php //Retrieve Theme Options Data
  global $options;
  $options = get_option('p2h_theme_options');

  echo $options['feedurl'];
  echo $options['cleanfeedurls'];
  ?>

 */

$p2h_options = array(
//Redes Sociais
    array("name" => "Redes Sociais",
        "type" => "section"),
    array("name" => "Endereço das redes sociais",
        "type" => "section-desc"),
    array("type" => "open"),
    array("name" => "Facebook",
        "desc" => "Endereço completo do Facebook",
        "id" => "facebook_url",
        "type" => "text",
        "std" => ""),
    array("name" => "Instagram",
        "desc" => "Endereço completo do instagram",
        "id" => "instagram_url",
        "type" => "text",
        "std" => ""),
    array("name" => "Twitter",
        "desc" => "Endereço completo do Twitter",
        "id" => "twitter_url",
        "type" => "text",
        "std" => ""),
    array("name" => "Youtube",
        "desc" => "Endereço completo do canal do Youtube",
        "id" => "youtube_url",
        "type" => "text",
        "std" => ""),
    array("name" => "Pinterest",
        "desc" => "Endereço completo do pinterest",
        "id" => "pinterest_url",
        "type" => "text",
        "std" => ""),
    array("type" => "close"),
//Codigos analytics
    array("name" => "Códigos analytics",
        "type" => "section"),
    array("name" => "Insira os códigos de scripts de rastreamento aqui",
        "type" => "section-desc"),
    array("type" => "open"),
    array("name" => "Códigos analytics",
        "desc" => "Você pode inserir os códigos de rastreamento do Google Analytics neste campo",
        "id" => "google_code",
        "type" => "textarea",
        "std" => null),
    array("name" => "Posição Códigos analytics",
        "desc" => "Defina a posição do códigos de rastreamento do Google Analytics",
        "id" => "posicao_google_code",
        "type" => "select",
        "options" => array('head', 'footer', 'body',),
        "std" => 'head'),
    array("type" => "close"),
    //Informacoes de contato
    array("name" => "Informações de contato",
        "type" => "section"),
    array("name" => "Insira as informações de contato",
        "type" => "section-desc"),
    array("type" => "open"),
    array("name" => "Razão Social do rodapé",
        "desc" => "Insira a razão social que será exibido no rodapé",
        "id" => "razao_social",
        "type" => "text",
        "std" => ""),
    array("name" => "CNPJ do rodapé",
        "desc" => "Insira o CNPJ que será exibido no rodapé",
        "id" => "cnpj",
        "type" => "text",
        "std" => ""),
    array("name" => "Nome",
        "desc" => "Insira o nome a ser exibido",
        "id" => "nome",
        "type" => "text",
        "std" => ""),
    array("name" => "E-mail",
        "desc" => "Insira o e-mail a ser exibido",
        "id" => "email",
        "type" => "text",
        "std" => ""),
    array("name" => "Endereço",
        "desc" => "Insira o endereço",
        "id" => "endereco",
        "type" => "textarea",
        "std" => ""),
    array("name" => "Telefone fixo",
        "desc" => "Informe um telefone para contato",
        "id" => "fone_1",
        "type" => "text",
        "std" => "(00) 0000-0000"),
    array("name" => "Telefone celular",
        "desc" => "Informe um telefone para contato",
        "id" => "fone_2",
        "type" => "text",
        "std" => "(00) 9 0000-0000"),
    array("name" => "Telefone whatsapp",
        "desc" => "Informe um telefone para contato (00) 9 0000-0000",
        "id" => "whatsapp",
        "type" => "text",
        "std" => "(00) 9 0000-0000"),
    array("name" => "Exibir whatsapp flutuante?",
        "desc" => "Marque para exibir o whatsapp flutuante.",
        "id" => "whatsapp_flutuante",
        "type" => "checkbox",
        "std" => ""),
    array("name" => "Posição do whatsapp flutuante",
        "desc" => "Defina a posição do whatsapp flutuante",
        "id" => "whatsapp_flutuante_position",
        "type" => "select",
        "options" => array('Esquerdo', 'Direito'),
        "std" => 'Direito'),
    array("name" => "Horário de atendimento",
        "desc" => "Informe o horário de atendimento",
        "id" => "atendimento",
        "type" => "text",
        "std" => ""),
    array("name" => "Texto do rodapé",
        "desc" => "Insira o texto que será exibido no rodapé",
        "id" => "footer_text",
        "type" => "textarea",
        "std" => null),
    array("type" => "close"),
);
?>